### ISSUE TITLE
--server-script-down is not executed if glasscoder is beeing terminated (SIGTERM)

### ISSUE THREAD

**Issue by saschaludwig** [ElvishArtisan/GlassCoder#3]
Looks like the --server-script-down is not executed or hasn't enough time to finish when glasscoder is beeing terminated via SIGTERM / Ctrl-C or when beeing terminated by glassgui

I would like to use the up+down script to switch on/off  "Stream Running" lamps in the studio and some other things.

Any ideas on that?
The main cause I use the gui is because of the nice stereometer. :-)
Would be nice to have both, stereometer and a down script beeing executed if the streaming is stopped via "Stop" button.

Kind regards, Sascha

**Comment by ElvishArtisan** [comment]
Fixed in master.

**Comment by saschaludwig** [comment]
Hi Fred, thanks for looking into this, but it still doesn't work here.
So I tried to understand your code but got lost somwhere because I did not completely understand how this whole connect/reconnect and conn_connected thing is supposed to work.
This is what I hunted down so far:

in src/glasscoder/connector.cpp:
in void Connector::stop() on line 337 you call setConnected(false);

In setConnected() at the very end in line 631 you set conn_connected=state;
So the conn_connected is set to 'false'

After returning from that function you have an:
in line 342  if(conn_connected&&(!conn_script_down.isEmpty())) {

which evaluates to false, so the script is not executed. But why?
should conn_connected==true at this point?

This leaves me a bit puzzled, and I can't see where this thing got screwed up :)

Maybe you could just look into it again and give me a hint :-)

**Comment by saschaludwig** [comment]
@ElvishArtisan I did some trial and error and moved the setConnected(false); below the syncronous script execution point. This solves my problem and the script is beeing executed on SIGTERM, "Stop" from glassgui and on server side disconnect.

https://github.com/saschaludwig/GlassCoder/commit/1ef1a17d9e41fef7179efe7e3385000b0adfce70

I don't know if this is a good solution or has shitloads of other unintended sideeffects.
So I decided not to make a pull request out of it :)
